### ISSUE TITLE
Failing to execute commands

### ISSUE THREAD

**Issue by Sierra1011** [samlader/gmux#2]
Installed v0.2.0 with pip.
Running any command results in this output:
```
❯ gmux init
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/3.10.5/bin/gmux", line 5, in <module>
    from gmux.cli import gmux
  File "/home/user/.pyenv/versions/3.10.5/lib/python3.10/site-packages/gmux/cli.py", line 198
    click.echo(f"cloning {org}/{repository["name"]}")
                                            ^^^^
SyntaxError: f-string: unmatched '['
```

**Comment by Sierra1011** [comment]
v0.2.1 fixed this, thank you!
